CREATE DATABASE PROYECTOBD2
USE PROYECTOBD2


CREATE TABLE PERSONA(
	idPersona INT NOT NULL,
	idTelefono INT NOT NULL,
	DUI CHAR(10),
	nombres VARCHAR (40) NOT NULL,
	apellidos VARCHAR(40)NOT NULL,
	correo VARCHAR(60),
	direccion VARCHAR(50)NOT NULL,
	institucion VARCHAR(10)NOT NULL,
	cargo CHAR (1)NOT NULL--LE PUSIMOS CARGO A LA VARIABLE Y REPRESENTA SI ES OBSERVADOR O SUPERVISOR
)
ALTER TABLE PERSONA ADD PRIMARY KEY (idPersona)
ALTER TABLE PERSONA ADD FOREIGN KEY (idTelefono) REFERENCES TELEFONO (idTelefono)
CREATE TABLE TELEFONO (
--VARIABLE QUE REPRESENTA SI EL USUARIO TIENE CELULAR O NO
	poseeCelular CHAR (1),
	marca VARCHAR(15) NOT NULL,
	modelo VARCHAR (15) NOT NULL,
	sistemaOperativo VARCHAR(7),
	versionOS VARCHAR (10),
	numeroCelular VARCHAR(9),
	numeroFijo VARCHAR (9),
	compania VARCHAR (15),
	idTelefono INT NOT NULL
)
ALTER TABLE TELEFONO ADD PRIMARY KEY (idTelefono)

CREATE TABLE DEPARTAMENTO(
	nombreDepartamento VARCHAR(15),
	idDepartamento INT NOT NULL
)
ALTER TABLE DEPARTAMENTO ADD PRIMARY KEY (idDepartamento)

CREATE TABLE MUNICIPIO(
	nombreMunicipio VARCHAR (15),
	idMunicipio INT NOT NULL
)
ALTER TABLE MUNICIPIO ADD PRIMARY KEY (idMunicipio)

CREATE TABLE CENTROVOTACION (
	nombreCentroVotacion VARCHAR (15),
	idCentroVotacion INT NOT NULL,
	idEncuesta INT NOT NULL
)
ALTER TABLE CENTROVOTACION ADD PRIMARY KEY (idCentroVotacion,idEncuesta)
ALTER TABLE CENTROVOTACION ADD FOREIGN KEY (idEncuesta) REFERENCES ENCUESTA (idEncuesta)
--TABLA QUE RELACIONA EL ID DE DEPARTAMENTO,MUNICIPIO Y CENTRO DE VOTACION

CREATE TABLE DEPARTAMENTOxMUNICIPIO(
	idDepartamento INT NOT NULL,
	idMunicipio INT NOT NULL,
	idCentroVotacion INT NOT NULL
)
ALTER TABLE DEPARTAMENTOxMUNICIPIO ADD PRIMARY KEY(idDepartamento, idMunicipio,idCentroVotacion);
ALTER TABLE DEPARTAMENTOxMUNICIPIO ADD FOREIGN KEY (idDepartamento) REFERENCES DEPARTAMENTO (idDepartamento);
ALTER TABLE DEPARTAMENTOxMUNICIPIO ADD FOREIGN KEY (idMunicipio ) REFERENCES MUNICIPIO (idMunicipio);
--AÑADIENDO LLAVE FK DE CENTROVOTACION
ALTER TABLE DEPARTAMENTOxMUNICIPIO ADD FOREIGN KEY(idCentroVotacion) REFERENCES CENTROVOTACION(idCentroVotacion)

CREATE TABLE PREGUNTA_MULTIPLE (

	idPreguntaMultiple INT NOT NULL,
	respuestaPregunta CHAR (1),

)
ALTER TABLE PREGUNTA_MULTIPLE ADD PRIMARY KEY (idPreguntaMultiple)


CREATE TABLE PREGUNTA_AGREGACION(
	idPreguntaAgregacion INT NOT NULL,
	respuestaAgregacion INT NOT NULL,
)
ALTER TABLE PREGUNTA_AGREGACION ADD PRIMARY KEY (idPreguntaAgregacion)
--TABLA ENCUESTA ES LA TABLA CRUZ ENTRE PREGUNTA MULTIPLE Y PREGUNTA DE AGREGACION

CREATE TABLE ENCUESTA(
	idEncuesta INT NOT NULL,
	idPreguntaMultiple INT NOT NULL,
	idPreguntaAgregacion INT NOT NULL,
	idPersona int not null
	--idObservador INT NOT NULL
)
ALTER TABLE ENCUESTA ADD PRIMARY KEY (idEncuesta,idPreguntaMultiple,idPreguntaAgregacion,idPersona)
ALTER TABLE ENCUESTA ADD FOREIGN KEY (idPreguntaMultiple)REFERENCES PREGUNTA_MULTIPLE(idPreguntaMultiple)
ALTER TABLE ENCUESTA ADD FOREIGN KEY (idPreguntaAgregacion)REFERENCES PREGUNTA_AGREGACION(idPreguntaAgregacion)
ALTER TABLE ENCUESTA ADD FOREIGN KEY (idPersona) REFERENCES PERSONA(idPersona)